//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Functions -------------------------

int main(int argc, char ** argv) {
    char buf[1024];
    if (argc == 1) {
        printf("%s [file to read]\n", (char *)*(int32_t *)argv);
        exit(1);
        // UNREACHABLE
    }
    //get &argv[1]
    int32_t * str = argv[0];
    //check if the path contains 'token'
    char * substr_pos = strstr((char *)*str, "token");
    char * path = (char *)*str;
    //if token was found, return
    if (substr_pos != 0) {
        printf("You may not access '%s'\n", path);
        exit(1);
    }
    // open and read file
    int32_t fd = open(path, O_RDONLY);
    if (fd == -1) {
        err(1, "Unable to open %s", (char *)*str);
        // branch -> 0x804862e
    }
    int32_t nbyte = read(fd, (int32_t *)&buf, 1024);
    if (nbyte == -1) {
        err(1, "Unable to read fd %d", fd);
        // branch -> 0x8048671
    }
    // display the file
    int32_t v1 = write(1, (int32_t *)&buf, nbyte);
    int32_t result;
    if (*(int32_t *)20 != *(int32_t *)20) {
        __stack_chk_fail();
        int32_t * v2;
        result = (int32_t)&v2;
        // branch -> 0x80486a2
    } else {
        result = v1;
    }
    return result;
}