//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Functions -------------------------

// From module:   /home/user/level07/level07.c
// Address range: 0x8048514 - 0x80485a1
// Line range:    6 - 24
int main(int argc, char ** argv) {
    int32_t v1 = getegid(); // 0x804851d
    int32_t v2 = geteuid(); // 0x8048526
    setresgid(v1, v1, v1);
    setresuid(v2, v2, v2);
    char * buffer = NULL; // bp-28
    char * env_val = getenv("LOGNAME"); // 0x8048576
    asprintf(&buffer, "/bin/echo %s ", env_val);
    return system(buffer);
}
